/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification for Gaon Delivery
 * OpenAPI spec version: 0.1.0
 */
import type { OrderItem } from "./orderItem";

export interface Order {
  id: number;
  customerName: string;
  address: string;
  phone?: string;
  items: OrderItem[];
  totalAmount: number;
  notes?: string;
  status: string;
  createdAt: Date;
}
